// Conjuntos de heurísticas, princípios e diretrizes de usabilidade.
// Códigos: prefixo do conjunto + número do item. Os nomes seguem traduções usuais em português.
window.HEUR = [
 {id:"NI", n:"Nielsen", fonte:"Jakob Nielsen, 1994 (rev. 2020)", d:"As 10 heurísticas de usabilidade mais usadas em avaliação heurística.", itens:[
  ["NI1","Visibilidade do status do sistema","O sistema mantém a pessoa informada sobre o que está acontecendo, com retorno adequado e em tempo razoável."],
  ["NI2","Correspondência com o mundo real","Fala a língua de quem usa: palavras, conceitos e ordem natural, em vez de termos internos do sistema."],
  ["NI3","Controle e liberdade do usuário","Saídas de emergência claras: desfazer, refazer, cancelar e voltar sem longos diálogos."],
  ["NI4","Consistência e padrões","A mesma coisa sempre com o mesmo nome, lugar e aparência — dentro do produto e em relação às convenções da plataforma."],
  ["NI5","Prevenção de erros","Melhor que boa mensagem de erro é um design que impede o erro de acontecer."],
  ["NI6","Reconhecer em vez de lembrar","Objetos, ações e opções visíveis; a pessoa não precisa guardar informação de uma tela para outra."],
  ["NI7","Flexibilidade e eficiência de uso","Aceleradores invisíveis para novatos servem aos experientes; o sistema atende os dois."],
  ["NI8","Estética e design minimalista","Cada informação extra compete com a relevante e reduz sua visibilidade."],
  ["NI9","Reconhecer, diagnosticar e recuperar erros","Mensagens em linguagem simples, que indicam o problema com precisão e sugerem a solução."],
  ["NI10","Ajuda e documentação","Ajuda fácil de buscar, focada na tarefa, com passos concretos e curta."]]},
 {id:"BS", n:"Bastien & Scapin", fonte:"Christian Bastien e Dominique Scapin, 1993 — critérios ergonômicos", d:"8 critérios principais desdobrados em 18 critérios elementares; muito usados no ensino de IHC no Brasil.", itens:[
  ["BS1.1","Condução: presteza","A interface convida e orienta: diz o que pode ser feito e como."],
  ["BS1.2","Condução: agrupamento por localização","Itens relacionados ficam próximos; itens diferentes, separados."],
  ["BS1.3","Condução: agrupamento por formato","Formato, cor e forma indicam a que grupo cada item pertence."],
  ["BS1.4","Condução: feedback imediato","Toda ação recebe resposta rápida e compreensível."],
  ["BS1.5","Condução: legibilidade","Texto e elementos visuais fáceis de ler: contraste, tamanho, espaçamento."],
  ["BS2.1","Carga de trabalho: concisão","Pouco a ler e a digitar; entradas e rótulos curtos."],
  ["BS2.2","Carga de trabalho: ações mínimas","O menor número de passos para chegar ao objetivo."],
  ["BS2.3","Carga de trabalho: densidade informacional","Só a informação necessária na tela, sem sobrecarga."],
  ["BS3.1","Controle explícito: ações explícitas","O sistema só faz o que a pessoa pediu explicitamente."],
  ["BS3.2","Controle explícito: controle do usuário","A pessoa pode interromper, cancelar, pausar e retomar."],
  ["BS4.1","Adaptabilidade: flexibilidade","Mais de uma forma de fazer a mesma tarefa."],
  ["BS4.2","Adaptabilidade: experiência do usuário","Atende novatos e experientes, cada um no seu ritmo."],
  ["BS5.1","Gestão de erros: proteção contra erros","O design previne erros antes que aconteçam."],
  ["BS5.2","Gestão de erros: qualidade das mensagens","Mensagens claras, específicas, construtivas e educadas."],
  ["BS5.3","Gestão de erros: correção dos erros","Corrigir é fácil e não obriga a recomeçar."],
  ["BS6","Homogeneidade e coerência","Escolhas de design mantidas em contextos idênticos."],
  ["BS7","Significado dos códigos e denominações","Nomes, ícones e códigos têm relação clara com o que representam."],
  ["BS8","Compatibilidade","A interface combina com as características, expectativas e tarefas de quem usa."]]},
 {id:"SH", n:"Shneiderman", fonte:"Ben Shneiderman — 8 regras de ouro do design de interfaces", d:"Regras clássicas do livro Designing the User Interface.", itens:[
  ["SH1","Buscar consistência","Sequências, termos, cores e layouts coerentes em situações semelhantes."],
  ["SH2","Atender à usabilidade universal","Considerar pessoas diversas: novatos, experientes, idades, deficiências, culturas."],
  ["SH3","Oferecer feedback informativo","Toda ação tem resposta proporcional à sua importância."],
  ["SH4","Projetar diálogos que indiquem término","Sequências com começo, meio e fim claros, com fechamento."],
  ["SH5","Prevenir erros","Tornar o erro grave difícil e oferecer correção simples."],
  ["SH6","Permitir reversão fácil de ações","Desfazer reduz a ansiedade e estimula a exploração."],
  ["SH7","Manter o usuário no controle","A pessoa inicia as ações; o sistema responde."],
  ["SH8","Reduzir a carga da memória de curto prazo","Não exigir que se lembre informações de uma tela para outra."]]},
 {id:"DN", n:"Norman", fonte:"Don Norman — O design do dia a dia (1988/2013)", d:"Princípios fundamentais de design centrado no ser humano.", itens:[
  ["DN1","Visibilidade","As funções e o estado importantes estão à vista."],
  ["DN2","Feedback","Cada ação comunica seu resultado."],
  ["DN3","Restrições","Limitar as ações possíveis para evitar as erradas."],
  ["DN4","Mapeamento","Relação natural entre controle e efeito."],
  ["DN5","Consistência","Operações e elementos semelhantes funcionam de forma semelhante."],
  ["DN6","Affordance","As propriedades do objeto sugerem como usá-lo."],
  ["DN7","Significantes","Sinais que indicam onde e como agir."],
  ["DN8","Modelo conceitual","Uma explicação simples de como o sistema funciona, compatível com a mente de quem usa."]]},
 {id:"TG", n:"Tognazzini", fonte:"Bruce Tognazzini — First Principles of Interaction Design (2014)", d:"Princípios de design de interação (a Lei de Fitts, também listada por ele, está em Leis de UX).", itens:[
  ["TG1","Antecipação","Oferecer o que a pessoa vai precisar antes que peça."],
  ["TG2","Autonomia","A pessoa decide, dentro de limites claros, e sabe o estado das coisas."],
  ["TG3","Cor e daltonismo","Cor nunca é o único portador de informação."],
  ["TG4","Consistência","Consistência visual e de comportamento, sem impedir a evolução."],
  ["TG5","Padrões (defaults)","Valores iniciais úteis, fáceis de trocar, que não prejudicam."],
  ["TG6","Descobribilidade","Recursos precisam ser encontráveis; o que não se vê não se usa."],
  ["TG7","Eficiência do usuário","Otimizar o tempo da pessoa, não o do computador."],
  ["TG8","Interfaces exploráveis","Explorar sem medo, com saídas e caminhos de volta."],
  ["TG9","Objetos de interface humanos","Objetos que se comportam de forma previsível, como coisas do mundo."],
  ["TG10","Redução de latência","Responder rápido e mostrar progresso quando não der."],
  ["TG11","Aprendizagem","Fácil de aprender e de lembrar."],
  ["TG12","Metáforas","Metáforas que evocam o modelo certo, sem prometer o que não cumprem."],
  ["TG13","Proteger o trabalho do usuário","Nunca deixar que a pessoa perca o que fez."],
  ["TG14","Legibilidade","Texto com contraste e tamanho adequados."],
  ["TG15","Rastrear o estado","Guardar onde a pessoa estava e o que fazia."],
  ["TG16","Navegação visível","Evitar navegação invisível; mostrar onde se está e para onde se pode ir."],
  ["TG17","Simplicidade","Reduzir complexidade sem reduzir capacidade."],
  ["TG18","Estética","Aparência cuidada que aumenta a confiança e o prazer de uso."]]},
 {id:"GP", n:"Gerhardt-Powals", fonte:"Jill Gerhardt-Powals — princípios de engenharia cognitiva (1996)", d:"Princípios voltados a reduzir a carga cognitiva.", itens:[
  ["GP1","Automatizar a carga indesejada","Cálculos, estimativas e comparações ficam com o sistema."],
  ["GP2","Reduzir a incerteza","Dados claros e óbvios; nada a adivinhar."],
  ["GP3","Fundir dados","Juntar dados de baixo nível em informação de alto nível."],
  ["GP4","Apresentar o novo com auxílios de interpretação","Informação nova vem com referências conhecidas (metáforas, comparações)."],
  ["GP5","Nomes ligados à função","Rótulos e ícones relacionados conceitualmente ao que fazem."],
  ["GP6","Agrupar de forma consistente e significativa","Agrupamentos lógicos que facilitam a busca."],
  ["GP7","Limitar tarefas orientadas a dados","Reduzir o tempo gasto assimilando dados crus."],
  ["GP8","Só a informação necessária no momento","Excluir o que não é relevante para a tarefa atual."],
  ["GP9","Múltiplas codificações quando apropriado","Mais de uma forma (texto, gráfico, cor) para dados importantes."],
  ["GP10","Redundância criteriosa","Repetir o essencial onde isso reduz erros, sem exagero."]]},
 {id:"ISO", n:"ISO 9241-110", fonte:"ISO 9241-110:2020 — Ergonomia da interação humano-sistema: princípios de interação", d:"Norma internacional com 7 princípios de interação.", itens:[
  ["ISO1","Adequação às tarefas do usuário","O sistema apoia a tarefa real, sem passos desnecessários."],
  ["ISO2","Autodescrição","A pessoa entende onde está, o que pode fazer e como."],
  ["ISO3","Conformidade com as expectativas","Comportamento previsível e alinhado a convenções."],
  ["ISO4","Facilidade de aprendizagem","Descobrir e aprender o uso com pouco esforço."],
  ["ISO5","Controlabilidade","A pessoa controla direção, ritmo e momento da interação."],
  ["ISO6","Robustez ao erro de uso","Evitar erros, tolerá-los e facilitar a recuperação."],
  ["ISO7","Engajamento do usuário","Interação convidativa e motivadora, que gera confiança."]]},
 {id:"WC", n:"WCAG 2.2", fonte:"W3C — Web Content Accessibility Guidelines 2.2 (2023)", d:"4 princípios (perceptível, operável, compreensível, robusto) com 13 diretrizes de acessibilidade.", itens:[
  ["WC1.1","Perceptível: alternativas em texto","Todo conteúdo não textual tem equivalente em texto."],
  ["WC1.2","Perceptível: mídia baseada em tempo","Legendas, transcrições e audiodescrição para áudio e vídeo."],
  ["WC1.3","Perceptível: adaptável","A estrutura se mantém em outras apresentações (leitor de tela, zoom)."],
  ["WC1.4","Perceptível: distinguível","Contraste, redimensionamento e cor que não é o único sinal."],
  ["WC2.1","Operável: acessível por teclado","Toda função disponível pelo teclado."],
  ["WC2.2","Operável: tempo suficiente","Tempo para ler e agir, com pausa ou extensão."],
  ["WC2.3","Operável: convulsões e reações físicas","Nada que pisque mais de 3 vezes por segundo; movimento dispensável."],
  ["WC2.4","Operável: navegável","Títulos, foco visível, ordem lógica e caminhos para encontrar conteúdo."],
  ["WC2.5","Operável: modalidades de entrada","Alvos de tamanho adequado e gestos com alternativas simples."],
  ["WC3.1","Compreensível: legível","Linguagem clara, idioma identificado, siglas explicadas."],
  ["WC3.2","Compreensível: previsível","Nada muda de contexto sem aviso; navegação consistente."],
  ["WC3.3","Compreensível: assistência de entrada","Identificar erros, sugerir correção e prevenir enganos graves."],
  ["WC4.1","Robusto: compatível","Funciona com tecnologias assistivas atuais e futuras."]]},
 {id:"MB", n:"Bertini (móvel)", fonte:"Enrico Bertini, Silvia Gabrielli e Stephen Kimani — heurísticas para computação móvel (2006)", d:"Heurísticas adaptadas a celulares e dispositivos portáteis.", itens:[
  ["MB1","Status do sistema e localizabilidade do dispositivo","Informar estado e contexto; o aparelho e o app são fáceis de achar e retomar."],
  ["MB2","Correspondência com o mundo real","Conteúdo e interação ligados ao contexto físico de uso."],
  ["MB3","Consistência e mapeamento","Controles físicos e virtuais mapeados de forma previsível."],
  ["MB4","Boa ergonomia e design minimalista","Uso com uma mão, em movimento; só o essencial na tela pequena."],
  ["MB5","Entrada fácil, leitura e olhar rápido","Pouca digitação, texto legível, informação captada num relance."],
  ["MB6","Flexibilidade, eficiência e personalização","Atalhos, ajustes e adaptação ao uso de cada pessoa."],
  ["MB7","Estética, privacidade e convenções sociais","Respeitar o uso em público: discrição, som, privacidade."],
  ["MB8","Gestão realista de erros","Considerar falhas de rede, bateria e interrupções, com recuperação."]]},
 {id:"LX", n:"Leis de UX", fonte:"Leis e efeitos da psicologia aplicados ao design (compilação de Jon Yablonski, 2020)", d:"Regularidades empíricas da percepção, memória e decisão humanas.", itens:[
  ["LX1","Lei de Fitts","O tempo para atingir um alvo depende da distância e do tamanho dele."],
  ["LX2","Lei de Hick","Mais opções, mais tempo para decidir."],
  ["LX3","Lei de Miller","A memória de trabalho guarda poucos itens; agrupar ajuda."],
  ["LX4","Lei de Jakob","As pessoas esperam que o seu site funcione como os outros que já conhecem."],
  ["LX5","Lei de Tesler","Toda tarefa tem uma complexidade que não some; alguém — sistema ou pessoa — arca com ela."],
  ["LX6","Limiar de Doherty","Respostas abaixo de ~400 ms mantêm o ritmo e a produtividade."],
  ["LX7","Lei de Postel","Seja tolerante com o que aceita e rigoroso com o que entrega."],
  ["LX8","Regra do pico-fim","A experiência é lembrada pelo seu pior momento e pelo final."],
  ["LX9","Efeito Von Restorff","O item diferente dos demais é o mais lembrado."],
  ["LX10","Gestalt: proximidade e região comum","Elementos próximos ou na mesma região são vistos como grupo."],
  ["LX11","Efeito Zeigarnik","Tarefas incompletas ficam na memória e pedem conclusão."],
  ["LX12","Gradiente de objetivo","A motivação cresce conforme o fim se aproxima."],
  ["LX13","Carga cognitiva","A capacidade mental é limitada; o excesso causa erros e abandono."]]},
 {id:"DP", n:"Dark patterns", fonte:"Colin Gray et al. — The Dark (Patterns) Side of UX Design (CHI 2018)", d:"Estratégias de design que agem contra o interesse de quem usa. Aqui servem para reconhecer e desfazer.", itens:[
  ["DP1","Insistência (nagging)","Interrupções repetidas para empurrar uma ação."],
  ["DP2","Obstrução","Tornar difícil o que a pessoa quer, para desestimulá-la."],
  ["DP3","Furtividade (sneaking)","Esconder ou atrasar informação relevante para a decisão."],
  ["DP4","Interferência na interface","Manipular a apresentação para favorecer uma opção."],
  ["DP5","Ação forçada","Exigir algo não relacionado para permitir o que se quer."]]},
 {id:"IA", n:"Humano-IA", fonte:"Saleema Amershi et al. (Microsoft) — Guidelines for Human-AI Interaction (CHI 2019)", d:"18 diretrizes para sistemas com inteligência artificial, recomendação ou automação.", itens:[
  ["IA1","Deixar claro o que o sistema pode fazer","Explicar a capacidade da IA."],
  ["IA2","Deixar claro quão bem ele faz","Comunicar a frequência de erros e a confiabilidade."],
  ["IA3","Agir no momento certo","Intervir conforme a tarefa e o contexto atuais."],
  ["IA4","Mostrar informação relevante ao contexto","Exibir o que importa para a tarefa e o ambiente."],
  ["IA5","Respeitar normas sociais","Agir e falar de modo socialmente adequado."],
  ["IA6","Mitigar vieses sociais","Evitar estereótipos e discriminação na linguagem e nas decisões."],
  ["IA7","Facilitar a invocação","Chamar o serviço de IA com facilidade quando necessário."],
  ["IA8","Facilitar a dispensa","Ignorar ou dispensar a IA com facilidade."],
  ["IA9","Facilitar a correção","Editar, refinar ou recuperar quando a IA erra."],
  ["IA10","Delimitar o serviço na dúvida","Na incerteza, pedir esclarecimento ou reduzir a ação."],
  ["IA11","Explicar o porquê","Deixar claro por que o sistema fez o que fez."],
  ["IA12","Lembrar interações recentes","Manter memória de curto prazo útil."],
  ["IA13","Aprender com o comportamento","Personalizar a partir do uso."],
  ["IA14","Atualizar e adaptar com cautela","Mudanças graduais, sem rupturas bruscas."],
  ["IA15","Incentivar feedback granular","Permitir indicar preferências de forma específica."],
  ["IA16","Comunicar consequências","Mostrar como as ações da pessoa afetam o comportamento futuro."],
  ["IA17","Oferecer controles globais","Ajustar globalmente o que a IA monitora e como se comporta."],
  ["IA18","Avisar sobre mudanças","Informar quando a IA ganha ou muda capacidades."]]}
];
